name: test-windows
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Run Tests
      shell: powershell
      run: |
        .\hack\test-windows.ps1
